# Generated by Django 6.0.4 on 2026-04-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_food_discoint_alter_food_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('foods', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
