# Generated by Django 6.0.4 on 2026-04-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='image',
        ),
        migrations.AddField(
            model_name='food',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
