# Generated by Django 6.0.4 on 2026-05-02 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_food_image_food_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='discoint',
            new_name='discount',
        ),
    ]
