# Generated by Django 6.0.4 on 2026-05-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_discoint_food_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Arabic Name'),
        ),
        migrations.AddField(
            model_name='food',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Arabic Description'),
        ),
        migrations.AddField(
            model_name='food',
            name='ingredients_ar',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Arabic Ingredients'),
        ),
        migrations.AddField(
            model_name='food',
            name='name_ar',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Arabic Name'),
        ),
    ]
