# Generated by Django 6.0.4 on 2026-06-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_order_options_rename_foods_order_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Final Price'),
        ),
    ]
