# Generated by Django 6.0.4 on 2026-06-20 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_food_final_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
    ]
