# Generated by Django 6.0.4 on 2026-07-08 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_name_customer_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
    ]
