# Generated by Django 6.0.4 on 2026-07-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_customer_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='is_takeaway',
            field=models.BooleanField(default=False, verbose_name='Takeaway'),
        ),
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Table Number'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
